import Head from 'next/head';
import { useRouter } from 'next/router';
import CustomHeader from '../pages/component/CustomHeader';
import CustomFooter from '../pages/component/CustomFooter';


export default function Home() {
  const router = useRouter();

  return (
    <>
      <div className="p-0">
        <Head>
          <title>CaMovie</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <CustomHeader>
        </CustomHeader>
        <main className="px-0 py-32 flex flex-col justify-center  items-center">
          <h1 className="m-0 leading-5 text-5xl text-center  text-indigo-900 ">
            Welcome to CaMovie!
          </h1>
          <div className="flex flex-row">
            <button type="button" onClick={() => router.push("/movies")} className="m-4 mt-12 flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700">
              &rarr; 馬上訂票
            </button>
            <button type="button" onClick={() => router.push("/memberCenter")} className="m-4 mt-12 flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200">
              &rarr; 訂單查詢
            </button>
          </div>
        </main>
        <CustomFooter>
        </CustomFooter>
      </div>
    </>

  )
}
